# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hw38CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hw38CocoaPods
  pod 'Alamofire'
  pod 'Fabric'
  pod 'Crashlytics'
end
